-- MySQL Script generated by MySQL Workbench
-- sex 12 mai 2023 13:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema alphacode_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alphacode_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alphacode_database` DEFAULT CHARACTER SET utf8 ;
USE `alphacode_database` ;

-- -----------------------------------------------------
-- Table `alphacode_database`.`tbl_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alphacode_database`.`tbl_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `profession` VARCHAR(250) NULL,
  `phone` VARCHAR(15) NULL,
  `cellphone` VARCHAR(20) NOT NULL,
  `checked_wpp` TINYINT(1) NULL DEFAULT 0,
  `checked_sms` TINYINT(1) NULL DEFAULT 0,
  `checked_email` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
);

INSERT INTO tbl_contact (
	name,
    birth_date,
    email,
    profession,
    phone,
    cellphone,
    checked_wpp,
    checked_sms,
    checked_email
) VALUES (
  	'Marina Santello Pimentel',
     '2004-10-12',
     'marinasantello.dev@gmail.com',
     'Desenvolvedora Mobile',
     null,
     '11956372791',
     1,
     0,
     0
),
(
	'Caio Costa',
    '2001-02-10',
	'caio@alphacode.com.br',
    'Líder técnico',
    '1199999999',
    '11999999999',
    1,
    1,
    1
),
(
	'Andréia Fernandes',
    '1993-01-19',
    'andreia@alphacode.com.br',
    'Analista Administrativo',
    null,
    '11999999999',
    0,
	0,
    1
);